{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "Fixed in the develop branch",
    "ClosedDate": "2013-10-11T13:23:22.503-07:00",
    "CommentCount": 1,
    "Custom": null,
    "Description": "Using Typescript 0.9.1.1, the reference to the \"Core\" module in the below code is optimized out even though it is used.\r\n\r\n``` TypeScript\r\ndeclare var Error: any;\r\n\r\nimport Core = require(\"Core\");\r\n\r\nexport class TestClass {\r\n    public errorHandler(error): void {\r\n        var error = Error.create(Core.StringUtils.format(\"Exception occured: '{0}'\", error.message));\r\n        throw error;\r\n    }\r\n}\r\n```\r\n\r\nThe referened module:\r\n\r\n``` TypeScript\r\nexport class StringUtils {\r\n    public static format(formatString: string, ...params: string[]) {\r\n    }\r\n}\r\n```",
    "LastUpdatedDate": "2013-10-11T13:23:22.503-07:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Unassigned",
      "Severity": 0,
      "Id": 0
    },
    "ProjectName": "typescript",
    "ReportedDate": "2013-10-11T09:45:35.687-07:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Fixed"
    },
    "Summary": "Module reference optimized out ",
    "Type": {
      "Name": "Unassigned",
      "Id": 5
    },
    "VoteCount": 1,
    "Id": 1781
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "Changing the error handler to use the module outside of the Error.create() call works around the issue:\n``` TypeScript\n    public errorHandler(error): void {\n        var result = Core.StringUtils.format(\"Exception occured: '{0}'\", error.message);\n        var error = Error.create(result);\n        throw error;\n    }\n\n```",
      "PostedDate": "2013-10-11T09:48:12.937-07:00",
      "Id": 118159
    }
  ]
}