{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "Thanks for logging this issue. We've moved to a new codebase on GitHub; please try your issue against the new compiler (once possible) and log an issue on the GitHub site if it still reproduces.",
    "ClosedDate": "2014-07-21T13:20:07.67-07:00",
    "CommentCount": 0,
    "Custom": null,
    "Description": "```\r\nmodule A {\r\n\tclass B {}\r\n\t\r\n\ttry { \r\n\t\t\r\n\t} catch (e) { \r\n\t\tvar xyz = new B();\r\n\t}\r\n}\r\n```\r\n\r\nThis report the compile error: `\"Exported variable 'xyz' has or is using private type 'A.B'.\"`. I'm guessing that it thinks the scope of the `catch () { ... }` block is the global scope, and since it exports the symbol `xyz` in the global object, it also expects B to be exported.\r\n\r\n",
    "LastUpdatedDate": "2017-11-27T11:51:34.217-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Unassigned",
      "Severity": 0,
      "Id": 0
    },
    "ProjectName": "typescript",
    "ReportedDate": "2014-03-10T12:12:39.47-07:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "External"
    },
    "Summary": "Wrong Scope in Catch Blocks",
    "Type": {
      "Name": "Unassigned",
      "Id": 5
    },
    "VoteCount": 1,
    "Id": 2293
  },
  "FileAttachments": [],
  "Comments": []
}